# This file was generated by GoReleaser. DO NOT EDIT.
cask "bartleby" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "6e5da347cbb755d7d229f91a9ed137f5a28cf59fb77da713879f1e677c3ec463"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
    on_intel do
      sha256 "8c924ef69eed59428568ea0ad6c38ea900d93762ecb2cc46379b7e5280c9b1ba"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
  end
  on_linux do
    on_arm do
      sha256 "cdf74402c89caa287b913e9809e9f95333a7f22e8a32cb7504d99acb8efba957"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_linux_arm64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
    on_intel do
      sha256 "c1e117acc0781018541bcb1a24a7ac40a5594e4c0883570d7036f540bf32c16d"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_linux_amd64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
  end

  name "bartleby"
  desc "Render reStructuredText documentation using Sphinx inside Docker"
  homepage "https://github.com/neuronsphere/hmd-cli-bartleby"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bartleby"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bartleby"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    bartleby requires Docker to run documentation builds.
    If you use Colima, make sure it is running:
      colima start
  EOS
end
