# This file was generated by GoReleaser. DO NOT EDIT.
cask "bartleby" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "f0b5f9b55e3b51a1ae66daed74fe920fe15533c347ca1e7fb8b34605f017d407"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d39e5f957ab0abae08d8fe6fd6efb56048b88abf3b08595784ede53b7ba2037"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d58fc07a4309ac79e25a945bc6b3ac0b6a0e580a4f5966c5db5130cdd269361f"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b20528cf3c078736448450ae01b055445fbda69172512bc0357813e0b0160915"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bartleby"
  desc "Render reStructuredText documentation using Sphinx inside Docker"
  homepage "https://github.com/neuronsphere/hmd-cli-bartleby"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bartleby"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bartleby"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    bartleby requires Docker to run documentation builds.
    If you use Colima, make sure it is running:
      colima start
  EOS
end
