# This file was generated by GoReleaser. DO NOT EDIT.
cask "bartleby" do
  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "aa98582971a9fd47cb4639ac3ea6e641e1e5b862e8f4337f21c5e23972e92791"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
    on_intel do
      sha256 "ac2b6c160bf33cdf2a7b4fd69dcaefec01538c819ad9824690dd2bc7ae206b39"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
  end
  on_linux do
    on_arm do
      sha256 "dea5d2062c557c1efd7b7293c81edcb0a5cb1b642e1755fb84dd772705c8139a"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_linux_arm64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
    on_intel do
      sha256 "8d57fc4e09f1597b22580e6b346148f92f4506fe1f74b93efc1c1dde6a8c8705"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/bartleby_#{version}_linux_amd64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
  end

  name "bartleby"
  desc "Render reStructuredText documentation using Sphinx inside Docker"
  homepage "https://github.com/neuronsphere/hmd-cli-bartleby"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bartleby"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bartleby"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    bartleby requires Docker to run documentation builds.
    If you use Colima, make sure it is running:
      colima start
  EOS
end
