# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsctl" do
  version "1.0.212"

  on_macos do
    on_arm do
      sha256 "0080b1d5315137fb1fb838f508401d7c9a3d29a352774fe24f8d502410c18f7c"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eae988167252c9ed06b33c132cfd5083637777cfcb35b1846137b038afb334bf"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77043ea89257713b71af92ffa4e5b86931a764734002fe749b81dd42ae0c10f7"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "68b3e08eee257832b99f26a6edd5b3957fd0c7f40cb81fd16c8f15b255adc70c"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nsctl"
  desc "Run the local NeuronSphere: a control plane and the environment substrate deployments sit on"
  homepage "https://github.com/neuronsphere/hmd-cli-neuronsphere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nsctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    nsctl needs Docker running, and an HMD_HOME. It does not default one --
    guessing would put its containers, volumes and network under a name no
    other HMD tool computes -- so export it or pass --home:

      export HMD_HOME=~/hmd
      nsctl control-plane start

    If you use Colima, make sure it is running:
      colima start
  EOS
end
