# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsctl" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr",
            args:         ["-dr", "com.apple.quarantine", "{{staged_path}}/nsctl"],
            must_succeed: false
      end
    end
  end

  version "1.0.232"

  on_macos do
    on_arm do
      sha256 "d9d4031042a7fd18bab1b3801ea3b84b677fd14b9796b6aa6f97a25beb1e6055"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7c5a410e45a955932d88e59f268a5773bcc3036347560767093a7b827a44156"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f966e34a1a2c4ed0b20d943da8155ff603c5ae0b9b6dda30bbaa2041b77405fe"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed305c0e2d08f1c91bfa8a93627e7993dcba5e614560eaa0b119de1345692157"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nsctl"
  desc "Run the local NeuronSphere: a control plane and the environment substrate deployments sit on"
  homepage "https://github.com/neuronsphere/hmd-cli-neuronsphere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsctl"

  # No zap stanza required

  caveats <<~EOS
    nsctl needs Docker running. Start here:

      nsctl quickstart

    It runs the host checks, settles HMD_HOME -- nsctl never guesses one,
    because a guessed home names containers and volumes no other HMD tool
    computes -- starts your first environment, and names every command
    before it runs it.

    By hand instead:

      export HMD_HOME=~/hmd
      nsctl env start

    If you use Colima, make sure it is running:
      colima start
  EOS
end
