# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsctl" do
  version "1.0.220"

  on_macos do
    on_arm do
      sha256 "99a5886bcf560652ece14f3dc17865963d7edd00af7e635ce4c2cb05e3359e77"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6494ac4d68dd4fe98e2297437cd259347b99d99f7ad8f5afa571ace10fedd239"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "38cafddd7b7fff7bbb34350460d9cff71bd89467d701bff729f726bd59c1d79a"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d8bd5af9b6fdbb0b9da2ff494e550d66ac61f1c1b5e23d9ae84403fa401e3b5"
      url "https://github.com/neuronsphere/hmd-cli-neuronsphere/releases/download/#{version}/nsctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nsctl"
  desc "Run the local NeuronSphere: a control plane and the environment substrate deployments sit on"
  homepage "https://github.com/neuronsphere/hmd-cli-neuronsphere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nsctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    nsctl needs Docker running, and an HMD_HOME. It does not default one --
    guessing would put its containers, volumes and network under a name no
    other HMD tool computes -- so export it or pass --home:

      export HMD_HOME=~/hmd
      nsctl control-plane start

    If you use Colima, make sure it is running:
      colima start
  EOS
end
