# This file was generated by GoReleaser. DO NOT EDIT.
cask "reqtrace" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "983f58362893ce68d28a360da88d7070bef9bee314b016e57efb71a8c0f43d60"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/reqtrace_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5b37db2263c4cd78e674abfe7c9ea942a24bcc3d0f1240673a4df1e91960f61"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/reqtrace_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "469de6e9cc3c839c6e2a65b6cad7dd7113b3ed22a9a5487d8f766f3f98aae14c"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/reqtrace_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8cfdecd7a4ad83249b899a84d3802565b2123bcf89f5ff31c38f12821037e18"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/reqtrace_#{version}_linux_amd64.tar.gz"
    end
  end

  name "reqtrace"
  desc "Generate and check a requirements traceability matrix from sphinx-needs directives and test annotations"
  homepage "https://github.com/neuronsphere/hmd-cli-bartleby/tree/main/src/go/reqtrace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reqtrace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reqtrace"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    reqtrace needs nothing else installed — no Docker, no Python.
    Run it from a repository with requirements in docs/requirements/:
      reqtrace -check
  EOS
end
