# This file was generated by GoReleaser. DO NOT EDIT.
cask "reqtrace" do
  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "a9877139ad73d948d23822a8aa97088cf55a0439fc3f036d0f119cf87d5255d3"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/reqtrace_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
    on_intel do
      sha256 "00ab17527c1c5fdb163c792ed6cb71f8eec2550a5807fbff04984bc46c61e3f2"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/reqtrace_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
  end
  on_linux do
    on_arm do
      sha256 "d4ada0f66baf8b424275a8a35e613ac372c61f253aa36e3ff4526b1138edeb4c"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/reqtrace_#{version}_linux_arm64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
    on_intel do
      sha256 "c20ef7fa32ba75dbcf990d3dd542bde1a86e1a48974cd2eb149674a4b50f45d7"
      url "https://github.com/neuronsphere/hmd-cli-bartleby/releases/download/v#{version}/reqtrace_#{version}_linux_amd64.tar.gz",
        verified: "github.com/neuronsphere/hmd-cli-bartleby"
    end
  end

  name "reqtrace"
  desc "Generate and check a requirements traceability matrix from sphinx-needs directives and test annotations"
  homepage "https://github.com/neuronsphere/hmd-cli-bartleby/tree/main/src/go/reqtrace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reqtrace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reqtrace"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    reqtrace needs nothing else installed — no Docker, no Python.
    Run it from a repository with requirements in docs/requirements/:
      reqtrace -check
  EOS
end
